### ISSUE TITLE
pod bin code 源码调试有问题呀

### ISSUE THREAD

**Issue by RichardClay** [MeetYouDevs/cocoapods-imy-bin#133]
NoMethodError - undefined method `key?' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources.rb:48:in `concrete_class_from_params'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources.rb:32:in `from_params'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources.rb:27:in `from_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/code.rb:110:in `fetch_external_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/code.rb:87:in `download_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/code.rb:73:in `block in add'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/code.rb:66:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/code.rb:66:in `add'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/code.rb:51:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by liu369069118** [comment]
我这边已经二进制化了。只是想使用下这个源码调试的工具，遇到了和上面这位研发一样的问题。
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/17472291/109457863-a95c1780-7a96-11eb-8435-324d2e757b02.png">
cocoapods的源码调用出错了，不知道有没有什么解决方案。
<img width="986" alt="image" src="https://user-images.githubusercontent.com/17472291/109457908-c09b0500-7a96-11eb-98af-d104c0ce4804.png">

**Comment by RichardClay** [comment]
> 我这边已经二进制化了。只是想使用下这个源码调试的工具，遇到了和上面这位研发一样的问题。
> <img alt="image" width="1061" src="https://user-images.githubusercontent.com/17472291/109457863-a95c1780-7a96-11eb-8435-324d2e757b02.png">
> cocoapods的源码调用出错了，不知道有没有什么解决方案。
> <img alt="image" width="986" src="https://user-images.githubusercontent.com/17472291/109457908-c09b0500-7a96-11eb-98af-d104c0ce4804.png">

这应该是个bug

**Comment by CY-0227** [comment]
遇到了相同得错误，请问怎么解决？

**Comment by 342261733** [comment]
同问

**Comment by wuzaozhou** [comment]
调试到也是这里的问题，请求有解决方案了么
def self.concrete_class_from_params(params)
   
      if params.key?(:podspec)
        PodspecSource
      elsif params.key?(:path)
        PathSource
      elsif Downloader.strategy_from_options(params)
        DownloaderSource
      end
    end

**Comment by wuzaozhou** [comment]
修改podfile。改成 pod 'xxxx', :podspec =>'xxxx',再执行下pod bin code，就是能链接删源码了
