### ISSUE TITLE
制作二进制失败

### ISSUE THREAD

**Issue by xiaojiekillua** [MeetYouDevs/cocoapods-imy-bin#159]
db和服务都起起来了，制作二进制总是失败
报TypeError - no implicit conversion of nil into String

### Error

```
TypeError - no implicit conversion of nil into String
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:164:in `exist?'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:164:in `block (2 levels) in generate_project'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:155:in `block in generate_project'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:154:in `generate_project'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:129:in `run_archive'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:57:in `run'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/Users/etekcity/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
```

请问是啥情况呢

**Comment by CveniEs** [comment]
我也遇到这个问题，请问大佬解决了嘛

**Comment by xiaojiekillua** [comment]
> 我也遇到这个问题，请问大佬解决了嘛

我也忘了怎么解决的了。。  podfile和podspec两个要在同一个目录下

**Comment by looha518** [comment]
> 我也遇到这个问题，请问大佬解决了嘛

这个一般是缺少podspec文件，猜测可能是插件未做缺省文件检测以及容错
