### ISSUE TITLE
pod bin auto

### ISSUE THREAD

**Issue by PggMan** [MeetYouDevs/cocoapods-imy-bin#164]
想请教下这是哪出了问题

➜  BinaryDemo pod bin auto
/Users/pengge/Desktop/Demo/BinaryDemo/.DS_Store
/Users/pengge/Desktop/Demo/BinaryDemo/BinaryDemo.xcworkspace
/Users/pengge/Desktop/Demo/BinaryDemo/Podfile_local
/Users/pengge/Desktop/Demo/BinaryDemo/BinaryDemo.xcodeproj
/Users/pengge/Desktop/Demo/BinaryDemo/Pods
/Users/pengge/Desktop/Demo/BinaryDemo/Podfile
/Users/pengge/Desktop/Demo/BinaryDemo/BinaryDemo
/Users/pengge/Desktop/Demo/BinaryDemo/Podfile.lock

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin auto
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.22.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : BinarySpecs - git - ssh://git@git.sprucetec.com:50022/gepeng01/BinarySpecs.git @ 87b7abc932ae355922e4b147506e5985d4e2b2b9

               CodeSpecs - git - ssh://git@git.sprucetec.com:50022/gepeng01/CodeSpecs.git @ d7125ee0d59b84c69090dfbfb713c333578e0ca9

               MCSpecs - git - ssh://git@git.sprucetec.com:50022/meicai-mobile/modularization/MCSpecs.git @ a848a85cfb894411e479197d932bf7b5a86da23f

               sprucetec-meicai-mobile-modularization-mcspecs - git - https://git.sprucetec.com/meicai-mobile/modularization/MCSpecs.git @ a848a85cfb894411e479197d932bf7b5a86da23f

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-binary                      : 0.4.4
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.1.3
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
use_frameworks!
#plugin 'cocoapods-binary'
inhibit_all_warnings!
   source 'https://cdn.cocoapods.org/'              # trunk
   source 'ssh://git@git.sprucetec.com:50022/meicai-mobile/modularization/MCSpecs.git' #私有库
   source 'ssh://git@git.sprucetec.com:50022/gepeng01/CodeSpecs.git'
platform :ios, '9.0'

target 'BinaryDemo' do
  pod 'A_Test', :binary => true
  pod 'AFNetworking', '4.0.1', :binary => true
end
```

### Error

```
TypeError - no implicit conversion of nil into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+nil+into+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - TypeError - no implicit conversion of nil into String
   https://github.com/CocoaPods/CocoaPods/issues/10007 [closed] [5 comments]
   11 Dec 2020

 - undefined method `map' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9953 [closed] [1 comment]
   30 Jul 2020

 - TypeError - no implicit conversion of nil into String
   https://github.com/CocoaPods/CocoaPods/issues/6381 [closed] [17 comments]
   21 Mar 2020

and 21 more at:
https://github.com/cocoapods/cocoapods/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

**Comment by HuangYuAlbert** [comment]
对，我也是这个错误，老哥你最后怎么解决的？
