### ISSUE TITLE
pod bin auto 失败

### ISSUE THREAD

**Issue by yky138495** [MeetYouDevs/cocoapods-imy-bin#168]
====== cocoapods-imy-bin 0.3.1.3 版本 ======== 

======  dev 环境 ========

======  dev 环境 ========

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin auto
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : gitee-ymgspecrepo - git - git@gitee.com:menggeyang/ymgSpecRepo.git @ 804c635d59172e026b84084d732741f9caca19ec
               spec_bin_dev - git - https://gitee.com/menggeyang/cocoapods-imy-bin-spec.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               specPodBin - git - git@gitee.com:menggeyang/cocoapods-imy-bin-spec.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               tuhu-specrepo - git - git@gitlab.tuhu.cn:tuhushop/ios/SpecRepo.git @ 4fb436851868197b144e3b5f2b7836ddf659629e
               tuhu-tuhuiospodspecs - git - git@gitlab.tuhu.cn:iOS/TuhuiOSPodSpecs.git @ aaecc9ef87d5508ce56a6126fe770515b66ca66b
               tuhushop - git - git@gitlab.tuhu.cn:tuhushop/ios/lib-common/specs.git @ 58cba2ea4514e2448c0ec44e3b8dffbf43d6a305
               ymgSpecRepo - git - git@gitee.com:menggeyang/ymgSpecRepo.git @ 804c635d59172e026b84084d732741f9caca19ec
```

### Plugins

```
cocoapods-binary                      : 0.4.4
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.1.3
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Error

```
TypeError - no implicit conversion of nil into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:164:in `exist?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:164:in `block (2 levels) in generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:155:in `block in generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:154:in `generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:129:in `run_archive'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:57:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+nil+into+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - TypeError - no implicit conversion of nil into String
   https://github.com/CocoaPods/CocoaPods/issues/10007 [closed] [5 comments]
   11 Dec 2020

 - undefined method `map' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9953 [closed] [1 comment]
   30 Jul 2020

 - TypeError - no implicit conversion of nil into String
   https://github.com/CocoaPods/CocoaPods/issues/6381 [closed] [17 comments]
   21 Mar 2020

and 21 more at:
https://github.com/cocoapods/cocoapods/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

[!] ====== cocoapods-imy-bin 0.3.1.3 版本 ======== 
 

[!] ======  dev 环境 ========

**Comment by wish-pig** [comment]
看下是否缺少一个 后.podspec 的文件，看代码里有检查，可以创建个空的 xxx.podspec 文件

**Comment by HMWDavid** [comment]
> 看下代码里有一个文件里的.podspec的，有检查的，可以创建一个空的xxx.podspec的
> 
> ![图片](https://user-images.githubusercontent.com/8498310/128588914-c2d2274b-3ea8-45c3-a9bb-3c40ed830bf4.png)

存在这个文件也报错呢
