### ISSUE TITLE
执行pod bin auto 报错

### ISSUE THREAD

**Issue by Jentlezhi** [MeetYouDevs/cocoapods-imy-bin#17]
### Error

```
NoMethodError - undefined method `target_definition_list' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/podfile_generator.rb:331:in `target_definition_list'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/podfile_generator.rb:290:in `supported_swift_versions'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_generator.rb:40:in `block in podfile_for_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:50:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `podfile_for_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/podfile_generator.rb:22:in `block in podfiles_by_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/podfile_generator.rb:21:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/podfile_generator.rb:21:in `podfiles_by_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/command/gen.rb:67:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:166:in `block (2 levels) in generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:153:in `block in generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:152:in `generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:124:in `run_archive'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:53:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60target_definition_list%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: Failed to open TCP connection to api.github.com:443 (Connection refused - connect(2) for "api.github.com" port 443)

[!] ====== cocoapods-imy-bin 0.2.9.1 版本 ========

[!] ======  dev 环境 ========

**Comment by su350380433** [comment]
用了podfile和podfile同级目录文件列表发出来看看

**Comment by Jentlezhi** [comment]
podfile 和 podspec不在同一级目录，必须把podfile移动到和podspec同级目录吗？

**Comment by su350380433** [comment]
是的

**Comment by Jentlezhi** [comment]
模板创建的podspec和podfile不在一个目录的，每次都要手动移动的话有一点点麻烦把，可以优化下吗

**Comment by su350380433** [comment]
不行
