### ISSUE TITLE
pod bin --help 都报错？？？

### ISSUE THREAD

**Issue by ljh740** [MeetYouDevs/cocoapods-imy-bin#171]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin --help
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 8d863c1c7e37f6ebf93de8b6ecc3c759b873b1fa

               *spec - git - http://*spec.git @ 605557b7885c25e18caf849ba56f4b27b675f1fe

               *specs - git - http://*specs.git @ bd2675d27bf5775090cd19906d08766dbaedde53

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.1.3
cocoapods-packager                    : 1.5.0
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
cocoapods-xcframework                 : 0.2.1
```

### Error

```
RuntimeError - Unable to find the default subcommand `open` for command `Pod::Command::Bin`.
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:368:in `load_default_subcommand'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:354:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by tomisacat** [comment]
➕1

```sh
$ pod plugins installed

Installed CocoaPods Plugins:
    - cocoapods-browser                     : 0.1.5
    - cocoapods-deintegrate                 : 1.0.4
    - cocoapods-disable-podfile-validations : 0.1.1
    - cocoapods-generate                    : 2.0.1
    - cocoapods-imy-bin                     : 0.3.1.3 (pre_install and source_provider hooks)
    - cocoapods-plugins                     : 1.0.0
    - cocoapods-search                      : 1.0.0
    - cocoapods-trunk                       : 1.5.0
    - cocoapods-try                         : 1.2.0
```

**Stack:**

```sh
   CocoaPods : 1.10.2
        Ruby : ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
    RubyGems : 3.2.22
        Host : macOS 11.5 (20G5023d)
       Xcode : 12.5 (12E262)
         Git : git version 2.32.0
Ruby lib dir : /usr/local/Cellar/ruby@2.7/2.7.4/lib
```

**Error:**

```sh
RuntimeError - Unable to find the default subcommand `open` for command `Pod::Command::Bin`.
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:368:in `load_default_subcommand'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:354:in `parse'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.2/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `<main>'
```

**Comment by SunXiangLong** [comment]
注释掉 bin.rb 里面的  # self.default_subcommand = 'open'   其中open命令是未定义的，在command.rb 中  会抛出异常
 
def self.load_default_subcommand(argv)
      unless subcommand = find_subcommand(default_subcommand)
        raise 'Unable to find the default subcommand ' \
          "`#{default_subcommand}` for command `#{self}`."
      end
      result = subcommand.parse(argv)
      result.invoked_as_default = true
      result
    end

**Comment by SunXiangLong** [comment]
@tomisacat @ljh740
