### ISSUE TITLE
Mac版本使用出现问题

### ISSUE THREAD

**Issue by 2Saber** [MeetYouDevs/cocoapods-imy-bin#193]
Analyzing dependencies
====== cocoapods-imy-bin 0.3.1.3 版本 ========
======  dev 环境 ========
======  dev 环境 ========

### Command

```
/usr/local/bin/pod install update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack
CocoaPods : 1.11.2
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.1 (21C52)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 2saber-jyb_spec - git - git@github.com:2Saber/JYB_spec.git @ 743e8c1d9032ee4aa324735c45696710c8c1e200

               JYB - git - git@github.com:2Saber/JYB.git @ 2eebee5f6df305b7bc774be345629fa58f06f859

               jyb_spec_bin_dev - git - git@github.com:2Saber/JYB_spec_bin.git @ 6e439ffa39a91e94b9d805932b5a4f0db6e16d96

               PrivatePods - git - https://github.com/ModulizationDemo/PrivatePods.git @ 727fb3add4fd6d34275a185841a1607f5b74bfd7

               su350380433-example_spec_bin_dev - git - git@github.com:su350380433/example_spec_bin_dev.git @ 04a94cd20abe9ab0cf131b80ddbf35071ad044df

               su350380433-example_spec_source - git - git@github.com:su350380433/example_spec_source.git @ 5a421ce7d5c61ff3cd761d44c751c72ccea3d3ff

               trunk - CDN - https://cdn.cocoapods.org/

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.1.3
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.4.1
cocoapods-try                         : 1.1.0

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
plugin 'cocoapods-imy-bin'
use_binaries!
#plugin 'cocoapods-githooks'

def baselib
pod 'Masonry'
pod 'CocoaAsyncSocket'
#pod 'GDataXML-HTML', '~> 1.4.1'
#pod 'ZipArchive'
pod 'NSPopover+MISSINGBackgroundView'
#pod 'Reachability'
#pod 'ReactiveCocoa', '~> 2.5'
#pod 'MASPreferences', '~> 1.3'
#pod 'matrix-wechat'
#pod 'CocoaLumberjack'
pod 'FMDB'
#pod 'SDWebImage'
end

def helplib
 #  pod 'KSLabel'
 #  pod 'SQLCipher', '~> 3.4.0'
end

platform :osx, '10.11'

target 'MAC_TradeBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  baselib



  target 'MAC_TradeBookTests' do
    inherit! :search_paths

  end

  target 'MAC_TradeBookUITests' do
    # Pods for testing
  end

end

### Error

```
Pod::StandardError - #<Pod::Specification::Consumer:0x00007fc2a7e7cdd8> is not compatible with osx.
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/consumer.rb:39:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:442:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:442:in `consumer'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:835:in `block in create_file_accessors'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:834:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:834:in `create_file_accessors'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:815:in `generate_pod_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:645:in `block (2 levels) in generate_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:643:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:643:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:643:in `block in generate_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:638:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:638:in `flat_map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:638:in `generate_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:431:in `generate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:127:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%23%3CPod%3A%3ASpecification%3A%3AConsumer%3A0x00007fc2a7e7cdd8%3E+is+not+compatible+with+osx.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Pod::StandardError - #<Pod::Specification::Consumer:0x007fabe9b0e5b8> is not compatible with osx.
   https://github.com/CocoaPods/CocoaPods/issues/2868 [closed] [4 comments]
   24 Nov 2014

 - An incompatibility that should be recognized and notified?
   https://github.com/CocoaPods/CocoaPods/issues/2906 [closed] [2 comments]
   04 Dec 2014

 - lints the current working directory [FAILED]
   https://github.com/CocoaPods/CocoaPods/issues/1708 [closed] [3 comments]
   05 Jan 2014

and 1 more at:
https://github.com/cocoapods/cocoapods/search?q=Pod%3A%3ASpecification%3A%3AConsumer%20is%20not%20compatible%20with%20osx.&type=Issues&utf8=✓

[!] ====== archive-white-pod-list = []

[!] ====== ignore_git_list = ["git@gitlab.xxx.com:Github-mac"]

[!] The platform of the target `MAC_TradeBook` (macOS 10.11) may not be compatible with `CocoaAsyncSocket (7.6.5)` which has a minimum requirement of iOS 9.0.

[!] The platform of the target `MAC_TradeBook` (macOS 10.11) may not be compatible with `Masonry (1.1.0)` which has a minimum requirement of iOS 6.0.

[!] The platform of the target `MAC_TradeBookUITests` (macOS 10.11) may not be compatible with `CocoaAsyncSocket (7.6.5)` which has a minimum requirement of iOS 9.0.

[!] The platform of the target `MAC_TradeBookUITests` (macOS 10.11) may not be compatible with `Masonry (1.1.0)` which has a minimum requirement of iOS 6.0.

我的.podspace文件
#
#  Be sure to run `pod spec lint MAC_TradeBook.podspec' to ensure this is a
#  valid spec and to remove all comments including this before submitting the spec.
#
#  To learn more about Podspec attributes see https://guides.cocoapods.org/syntax/podspec.html
#  To see working Podspecs in the CocoaPods repo see https://github.com/CocoaPods/Specs/
#

Pod::Spec.new do |spec|

  spec.name         = "MAC_TradeBook"
  spec.version      = "0.0.3"
  spec.summary      = "A short description of MAC_TradeBook."

  spec.description  = "JYB work"

  spec.homepage     = "https://github.com/2Saber/JYB.git"
    
  spec.license      = "MIT"

  spec.author             = { "2Saber" => "wwjwblc@163.com" }
  #spec.platform     = :osx, '10.10'
  s.platform              = :osx, '10.11'

  spec.source       = { :git => "git@github.com:2Saber/JYB.git", :branch => 'main' }

#  spec.source_files  = "Classes", "Classes/**/*.{h,m}"
 # spec.exclude_files = "Classes/Exclude"

  # spec.public_header_files = "Classes/**/*.h"
  
  

 spec.dependency 'Masonry'
 spec.dependency 'CocoaAsyncSocket'
 spec.dependency 'ZipArchive'
 #spec.dependency 'NSPopover+MISSINGBackgroundView'
 spec.dependency 'Reachability'
 spec.dependency 'ReactiveCocoa'

end

使用iOS终端时，是没有问题的。但使用mac时候，就出现不能pod update的情况。找了一下插件的原文件，没有找到插件一定是ios平台的

**Comment by HuiYouHua** [comment]
hello，问下你能依赖Moya 打成二进制包么
我这里如果库没有依赖其他库的话可以打成二进制
但是如果库依赖了其他库则会包找不到其他库的问题
比如这里Moya依赖了Alamofire，那再打包 Moya 时会报找不到 Alamofire
请问你有遇到这种情况么

我的qq：793316968
请加我一下
