### ISSUE TITLE
在制作二进制组件时候 pod bin auto --all-make 或者 pod bin auto  产生同一个问题

### ISSUE THREAD

**Issue by HMWDavid** [MeetYouDevs/cocoapods-imy-bin#208]
看了你们的文章后，我非常喜欢你们的这个方案，但是我在尝试使用的时候出现了一些问题。
以下是我做的一些配置，在处理到pod bin auto --all-make 产生了以下的问题，相信也有一些小伙伴也遇到了这个问题：

![截屏2022-04-29 16 05 38](https://user-images.githubusercontent.com/22783742/165906835-84d04dae-659c-4c7b-b402-029d0c96c409.png)

![截屏2022-04-29 16 03 25](https://user-images.githubusercontent.com/22783742/165906597-149bf222-5634-4924-a754-f61387c20e25.png)

![截屏2022-04-29 16 04 32](https://user-images.githubusercontent.com/22783742/165906700-864a3590-4e67-4f31-b50e-4ad8d06d9ead.png)

zk_01@zk-01deMac-mini ZKModule_Demo % 
zk_01@zk-01deMac-mini ZKModule_Demo % pod bin auto --all-make
/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/Podfile_local
/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/ZKModule_Demo.podspec
====== cocoapods-imy-bin 0.3.0.11 版本 ======== 

======  dev 环境 ========

======  dev 环境 ========
[pod gen] Running with `pod gen` configuration {         
  podfile_path: /Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/Podfile,         
  podfile: Podfile,         
  use_podfile: true,         
  use_podfile_plugins: true,         
  podfile_plugins: {"cocoapods-imy-bin"=>{}},         
  lockfile: #<Pod::Lockfile>,         
  use_lockfile: true,         
  use_lockfile_versions: true,         
  use_libraries: false,         
  generate_multiple_pod_projects: false,         
  incremental_installation: false,         
  gen_directory: /Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo-build-temp/bin-archive,         
  auto_open: false,         
  clean: true,         
  podspec_paths: [#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/ZKModule_Demo.podspec>, #<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/ZKModule_Demo.podspec>],         
  podspecs: [#<Pod::Specification name="ZKModule_Demo">, #<Pod::Specification name="ZKModule_Demo">],         
  sources: ["https://gitee.com/DaviesH/zkmodule_spec_bin_dev.git", "https://gitee.com/DaviesH/lxtspecs.git", "https://gitee.com/DaviesH/zkmodule_spec_bin_dev.git", "https://gitee.com/DaviesH/lxtspecs.git", "https://cdn.cocoapods.org"],         
  repo_update: false,         
  use_default_plugins: false,         
  deterministic_uuids: false,         
  share_schemes_for_development_pods: true,         
  warn_for_multiple_pod_sources: false,         
  use_modular_headers: false }

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/zk_01/.rvm/gems/ruby-3.0.0/bin/pod bin auto --all-make
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]
    RubyGems : 3.2.3
        Host : macOS 11.6 (20G165)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /Users/zk_01/.rvm/rubies/ruby-3.0.0/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 6bda3c3f4c3909456fc085084b5506d1f7535ad5

               gitee-daviesh-zkmodule_spec_bin_dev - git - https://gitee.com/DaviesH/zkmodule_spec_bin_dev.git @ e57bb05a2bfa30bbfbba9cb722ffab2c241af77d

               lxtspecs - git - https://gitee.com/DaviesH/lxtspecs.git @ 3d5325f141417fcc5bf2d84dccbdd8cdc87bb3f6

               master - git - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git @ c96e58acb571c7844eb113c18daf86c8bad57fbe

               PQCategory - git - http://172.29.151.11/ios/PQCategory.git @ 04911277571c859e00c4fc7eecf5944c05ac1d75

               PQSpecs - git - http://172.29.151.11/ios/pqspecs.git @ 6c6065a719192f2db272fb61069b946e50f2f1c3

               seongbrave-twilightspecs - git - https://github.com/seongbrave/TwilightSpecs.git @ 388856d8b2913d264da7074fb1877e126e65b8fc

               su350380433-example_spec_bin_dev - git - https://github.com/su350380433/example_spec_bin_dev.git @ 04a94cd20abe9ab0cf131b80ddbf35071ad044df

               su350380433-example_spec_source - git - https://github.com/su350380433/example_spec_source.git @ 5a421ce7d5c61ff3cd761d44c751c72ccea3d3ff

               trunk - CDN - https://cdn.cocoapods.org/
               ZKModule_spec_dev - git - https://gitee.com/DaviesH/ZKModule_spec_dev.git @ 3c74a5a70a3c38d9980a98f0459743d28e877085

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-generate    : 1.4.1
cocoapods-imy-bin     : 0.3.0.11
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://gitee.com/DaviesH/lxtspecs.git'

#plugin 'cocoapods-imy-bin'
#use_binaries!

use_frameworks!
#platform :ios, '13.0'

target 'ZKModule_Demo' do
  pod 'ModuleB' ,:git=>"https://gitee.com/DaviesH/module-b.git", :tag=>'0.0.3'
  pod 'ModuleA' ,'~> 0.1.1'
end
```

### Error

```
NoMethodError - undefined method `podfile_plugins' for #<Pod::Generate::PodfileGenerator:0x0000000139277358 @configuration=#<Pod::Generate::Configuration:0x000000013925e808 @pod_config=#<Pod::Config:0x00000001507023c0 @verbose=true, @silent=false, @skip_download_cache=false, @new_version_message=true, @cache_root=#<Pathname:/Users/zk_01/Library/Caches/CocoaPods>, @home_dir=#<Pathname:/Users/zk_01/.cocoapods>, @templates_dir=#<Pathname:/Users/zk_01/.cocoapods/templates>, @repos_dir=#<Pathname:/Users/zk_01/.cocoapods/repos>, @allow_root=nil, @sources_manager=#<Pod::Source::Manager:0x00000001507d0cc0 @repos_dir=#<Pathname:/Users/zk_01/.cocoapods/repos>, @sources_by_path={#<Pathname:/Users/zk_01/.cocoapods/repos/cocoapods>=>#<Pod::Source name:cocoapods type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/gitee-daviesh-zkmodule_spec_bin_dev>=>#<Pod::Source name:gitee-daviesh-zkmodule_spec_bin_dev type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/lxtspecs>=>#<Pod::Source name:lxtspecs type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/master>=>#<Pod::Source name:master type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/PQCategory>=>#<Pod::Source name:PQCategory type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/PQSpecs>=>#<Pod::Source name:PQSpecs type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/seongbrave-twilightspecs>=>#<Pod::Source name:seongbrave-twilightspecs type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/su350380433-example_spec_bin_dev>=>#<Pod::Source name:su350380433-example_spec_bin_dev type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/su350380433-example_spec_source>=>#<Pod::Source name:su350380433-example_spec_source type:git>, #<Pathname:/Users/zk_01/.cocoapods/repos/trunk>=>#<Pod::TrunkSource name:trunk type:CDN>, #<Pathname:/Users/zk_01/.cocoapods/repos/ZKModule_spec_dev>=>#<Pod::Source name:ZKModule_spec_dev type:git>}, @aggregates_by_repos={[#<Pathname:/Users/zk_01/.cocoapods/repos/cocoapods>, #<Pathname:/Users/zk_01/.cocoapods/repos/gitee-daviesh-zkmodule_spec_bin_dev>, #<Pathname:/Users/zk_01/.cocoapods/repos/lxtspecs>, #<Pathname:/Users/zk_01/.cocoapods/repos/master>, #<Pathname:/Users/zk_01/.cocoapods/repos/PQCategory>, #<Pathname:/Users/zk_01/.cocoapods/repos/PQSpecs>, #<Pathname:/Users/zk_01/.cocoapods/repos/seongbrave-twilightspecs>, #<Pathname:/Users/zk_01/.cocoapods/repos/su350380433-example_spec_bin_dev>, #<Pathname:/Users/zk_01/.cocoapods/repos/su350380433-example_spec_source>, #<Pathname:/Users/zk_01/.cocoapods/repos/trunk>, #<Pathname:/Users/zk_01/.cocoapods/repos/ZKModule_spec_dev>]=>#<Pod::Source::Aggregate:0x00000001391dcb00 @sources=[#<Pod::Source name:cocoapods type:git>, #<Pod::Source name:gitee-daviesh-zkmodule_spec_bin_dev type:git>, #<Pod::Source name:lxtspecs type:git>, #<Pod::Source name:master type:git>, #<Pod::Source name:PQCategory type:git>, #<Pod::Source name:PQSpecs type:git>, #<Pod::Source name:seongbrave-twilightspecs type:git>, #<Pod::Source name:su350380433-example_spec_bin_dev type:git>, #<Pod::Source name:su350380433-example_spec_source type:git>, #<Pod::TrunkSource name:trunk type:CDN>, #<Pod::Source name:ZKModule_spec_dev type:git>]>}>, @installation_root=#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo>, @podfile_path=#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/Podfile>, @podfile=#<Pod::Podfile:0x000000013919b768 @defined_in_file=#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/Podfile>, @internal_hash={"sources"=>["https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git", "https://gitee.com/DaviesH/lxtspecs.git"]}, @root_target_definitions=[#<Pod::Podfile::TargetDefinition label=Pods>], @current_target_definition=#<Pod::Podfile::TargetDefinition label=Pods>>, @lockfile_path=#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/Podfile.lock>, @lockfile=#<Pod::Lockfile>>, @podfile_path=#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/Podfile>, @podfile=#<Pod::Podfile:0x000000013925e588 @defined_in_file=#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/Podfile>, @internal_hash={"sources"=>["https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git", "https://gitee.com/DaviesH/lxtspecs.git"]}, @root_target_definitions=[#<Pod::Podfile::TargetDefinition label=Pods>], @current_target_definition=#<Pod::Podfile::TargetDefinition label=Pods>>, @use_podfile=true, @use_podfile_plugins=true, @podfile_plugins={"cocoapods-imy-bin"=>{}}, @lockfile=#<Pod::Lockfile>, @use_lockfile=true, @use_lockfile_versions=true, @use_libraries=false, @generate_multiple_pod_projects=false, @incremental_installation=false, @gen_directory=#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo-build-temp/bin-archive>, @auto_open=false, @clean=true, @app_host_source_dir=nil, @podspec_paths=[#<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/ZKModule_Demo.podspec>, #<Pathname:/Users/zk_01/Desktop/Demo/组件化探究/组件库/ ZKModule_spec_dev/ZKModule_Demo/ZKModule_Demo.podspec>], @podspecs=[#<Pod::Specification name="ZKModule_Demo">, #<Pod::Specification name="ZKModule_Demo">], @sources=["https://gitee.com/DaviesH/zkmodule_spec_bin_dev.git", "https://gitee.com/DaviesH/lxtspecs.git", "https://gitee.com/DaviesH/zkmodule_spec_bin_dev.git", "https://gitee.com/DaviesH/lxtspecs.git", "https://cdn.cocoapods.org"], @repo_update=false, @use_default_plugins=false, @deterministic_uuids=false, @share_schemes_for_development_pods=true, @warn_for_multiple_pod_sources=false, @use_modular_headers=false>>
Did you mean?  podfile_dependencies
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_generator.rb:34:in `block in podfile_for_spec'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:50:in `initialize'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `new'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `podfile_for_spec'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-generate-1.4.1/lib/cocoapods/generate/podfile_generator.rb:22:in `block in podfiles_by_spec'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-generate-1.4.1/lib/cocoapods/generate/podfile_generator.rb:21:in `map'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-generate-1.4.1/lib/cocoapods/generate/podfile_generator.rb:21:in `podfiles_by_spec'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-generate-1.4.1/lib/cocoapods/command/gen.rb:67:in `run'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/archive.rb:176:in `block (2 levels) in generate_project'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/archive.rb:155:in `block in generate_project'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/archive.rb:154:in `generate_project'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:126:in `run_archive'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:54:in `run'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/zk_01/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/zk_01/.rvm/gems/ruby-3.0.0/bin/pod:23:in `load'
/Users/zk_01/.rvm/gems/ruby-3.0.0/bin/pod:23:in `<main>'
/Users/zk_01/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/zk_01/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

It appears to have originated from your Podfile at line 0.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60podfile_plugins%27+for+%23%3CPod%3A%3AGenerate%3A%3APodfileGenerator%3A0x0000000139277358+%40configuration%3D%23%3CPod%3A%3AGenerate%3A%3AConfiguration%3A0x000000013925e808+%40pod_config%3D%23%3CPod%3A%3AConfig%3A0x00000001507023c0+%40verbose%3Dtrue%2C+%40silent%3Dfalse%2C+%40skip_download_cache%3Dfalse%2C+%40new_version_message%3Dtrue%2C+%40cache_root%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2FLibrary%2FCaches%2FCocoaPods%3E%2C+%40home_dir%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%3E%2C+%40templates_dir%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Ftemplates%3E%2C+%40repos_dir%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%3E%2C+%40allow_root%3Dnil%2C+%40sources_manager%3D%23%3CPod%3A%3ASource%3A%3AManager%3A0x00000001507d0cc0+%40repos_dir%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%3E%2C+%40sources_by_path%3D%7B%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fcocoapods%3E%3D%3E%23%3CPod%3A%3ASource+name%3Acocoapods+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fgitee-daviesh-zkmodule_spec_bin_dev%3E%3D%3E%23%3CPod%3A%3ASource+name%3Agitee-daviesh-zkmodule_spec_bin_dev+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Flxtspecs%3E%3D%3E%23%3CPod%3A%3ASource+name%3Alxtspecs+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fmaster%3E%3D%3E%23%3CPod%3A%3ASource+name%3Amaster+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2FPQCategory%3E%3D%3E%23%3CPod%3A%3ASource+name%3APQCategory+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2FPQSpecs%3E%3D%3E%23%3CPod%3A%3ASource+name%3APQSpecs+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fseongbrave-twilightspecs%3E%3D%3E%23%3CPod%3A%3ASource+name%3Aseongbrave-twilightspecs+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fsu350380433-example_spec_bin_dev%3E%3D%3E%23%3CPod%3A%3ASource+name%3Asu350380433-example_spec_bin_dev+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fsu350380433-example_spec_source%3E%3D%3E%23%3CPod%3A%3ASource+name%3Asu350380433-example_spec_source+type%3Agit%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Ftrunk%3E%3D%3E%23%3CPod%3A%3ATrunkSource+name%3Atrunk+type%3ACDN%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2FZKModule_spec_dev%3E%3D%3E%23%3CPod%3A%3ASource+name%3AZKModule_spec_dev+type%3Agit%3E%7D%2C+%40aggregates_by_repos%3D%7B%5B%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fcocoapods%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fgitee-daviesh-zkmodule_spec_bin_dev%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Flxtspecs%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fmaster%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2FPQCategory%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2FPQSpecs%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fseongbrave-twilightspecs%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fsu350380433-example_spec_bin_dev%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Fsu350380433-example_spec_source%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2Ftrunk%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2F.cocoapods%2Frepos%2FZKModule_spec_dev%3E%5D%3D%3E%23%3CPod%3A%3ASource%3A%3AAggregate%3A0x00000001391dcb00+%40sources%3D%5B%23%3CPod%3A%3ASource+name%3Acocoapods+type%3Agit%3E%2C+%23%3CPod%3A%3ASource+name%3Agitee-daviesh-zkmodule_spec_bin_dev+type%3Agit%3E%2C+%23%3CPod%3A%3ASource+name%3Alxtspecs+type%3Agit%3E%2C+%23%3CPod%3A%3ASource+name%3Amaster+type%3Agit%3E%2C+%23%3CPod%3A%3ASource+name%3APQCategory+type%3Agit%3E%2C+%23%3CPod%3A%3ASource+name%3APQSpecs+type%3Agit%3E%2C+%23%3CPod%3A%3ASource+name%3Aseongbrave-twilightspecs+type%3Agit%3E%2C+%23%3CPod%3A%3ASource+name%3Asu350380433-example_spec_bin_dev+type%3Agit%3E%2C+%23%3CPod%3A%3ASource+name%3Asu350380433-example_spec_source+type%3Agit%3E%2C+%23%3CPod%3A%3ATrunkSource+name%3Atrunk+type%3ACDN%3E%2C+%23%3CPod%3A%3ASource+name%3AZKModule_spec_dev+type%3Agit%3E%5D%3E%7D%3E%2C+%40installation_root%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo%3E%2C+%40podfile_path%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo%2FPodfile%3E%2C+%40podfile%3D%23%3CPod%3A%3APodfile%3A0x000000013919b768+%40defined_in_file%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo%2FPodfile%3E%2C+%40internal_hash%3D%7B%22sources%22%3D%3E%5B%22https%3A%2F%2Fmirrors.tuna.tsinghua.edu.cn%2Fgit%2FCocoaPods%2FSpecs.git%22%2C+%22https%3A%2F%2Fgitee.com%2FDaviesH%2Flxtspecs.git%22%5D%7D%2C+%40root_target_definitions%3D%5B%23%3CPod%3A%3APodfile%3A%3ATargetDefinition+label%3DPods%3E%5D%2C+%40current_target_definition%3D%23%3CPod%3A%3APodfile%3A%3ATargetDefinition+label%3DPods%3E%3E%2C+%40lockfile_path%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo%2FPodfile.lock%3E%2C+%40lockfile%3D%23%3CPod%3A%3ALockfile%3E%3E%2C+%40podfile_path%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo%2FPodfile%3E%2C+%40podfile%3D%23%3CPod%3A%3APodfile%3A0x000000013925e588+%40defined_in_file%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo%2FPodfile%3E%2C+%40internal_hash%3D%7B%22sources%22%3D%3E%5B%22https%3A%2F%2Fmirrors.tuna.tsinghua.edu.cn%2Fgit%2FCocoaPods%2FSpecs.git%22%2C+%22https%3A%2F%2Fgitee.com%2FDaviesH%2Flxtspecs.git%22%5D%7D%2C+%40root_target_definitions%3D%5B%23%3CPod%3A%3APodfile%3A%3ATargetDefinition+label%3DPods%3E%5D%2C+%40current_target_definition%3D%23%3CPod%3A%3APodfile%3A%3ATargetDefinition+label%3DPods%3E%3E%2C+%40use_podfile%3Dtrue%2C+%40use_podfile_plugins%3Dtrue%2C+%40podfile_plugins%3D%7B%22cocoapods-imy-bin%22%3D%3E%7B%7D%7D%2C+%40lockfile%3D%23%3CPod%3A%3ALockfile%3E%2C+%40use_lockfile%3Dtrue%2C+%40use_lockfile_versions%3Dtrue%2C+%40use_libraries%3Dfalse%2C+%40generate_multiple_pod_projects%3Dfalse%2C+%40incremental_installation%3Dfalse%2C+%40gen_directory%3D%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo-build-temp%2Fbin-archive%3E%2C+%40auto_open%3Dfalse%2C+%40clean%3Dtrue%2C+%40app_host_source_dir%3Dnil%2C+%40podspec_paths%3D%5B%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo%2FZKModule_Demo.podspec%3E%2C+%23%3CPathname%3A%2FUsers%2Fzk_01%2FDesktop%2FDemo%2F%E7%BB%84%E4%BB%B6%E5%8C%96%E6%8E%A2%E7%A9%B6%2F%E7%BB%84%E4%BB%B6%E5%BA%93%2F+ZKModule_spec_dev%2FZKModule_Demo%2FZKModule_Demo.podspec%3E%5D%2C+%40podspecs%3D%5B%23%3CPod%3A%3ASpecification+name%3D%22ZKModule_Demo%22%3E%2C+%23%3CPod%3A%3ASpecification+name%3D%22ZKModule_Demo%22%3E%5D%2C+%40sources%3D%5B%22https%3A%2F%2Fgitee.com%2FDaviesH%2Fzkmodule_spec_bin_dev.git%22%2C+%22https%3A%2F%2Fgitee.com%2FDaviesH%2Flxtspecs.git%22%2C+%22https%3A%2F%2Fgitee.com%2FDaviesH%2Fzkmodule_spec_bin_dev.git%22%2C+%22https%3A%2F%2Fgitee.com%2FDaviesH%2Flxtspecs.git%22%2C+%22https%3A%2F%2Fcdn.cocoapods.org%22%5D%2C+%40repo_update%3Dfalse%2C+%40use_default_plugins%3Dfalse%2C+%40deterministic_uuids%3Dfalse%2C+%40share_schemes_for_development_pods%3Dtrue%2C+%40warn_for_multiple_pod_sources%3Dfalse%2C+%40use_modular_headers%3Dfalse%3E%3E%0ADid+you+mean%3F++podfile_dependencies&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

[!] cocoapods-generate requires CocoaPods >= 1.5.0

[!] ====== cocoapods-imy-bin 0.3.0.11 版本 ======== 
 

[!] ======  dev 环境 ======== 
 
zk_01@zk-01deMac-mini ZKModule_Demo % 
zk_01@zk-01deMac-mini ZKModule_Demo %

**Comment by ztq123456** [comment]
这个插件学习成本太高了，我搞了两天，环境搭建，创建库前面遇到各种问题一个个解决了，在pod bin auto 这一步 一直卡在 NoMethodError - undefined method `podfile_plugins'  这个错误上一天多了，无解了，打算放弃。

**Comment by lin333** [comment]
解决了吗 我M1也通不了
