### ISSUE TITLE
貌似这执行都报错, 这库还有在维护吗?

### ISSUE THREAD

**Issue by rgmyyw** [MeetYouDevs/cocoapods-imy-bin#218]
$ pod bin

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/username/.rvm/gems/ruby-3.0.0/bin/pod bin
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.14.2
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin22]
    RubyGems : 3.4.22
        Host : macOS 13.5.2 (22G91)
       Xcode : 15.1 (15C5059c)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /Users/username/.rvm/rubies/ruby-3.0.0/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 8d29e3a786c4359f4deb77a073cc6291114e58d6

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.5
cocoapods-disable-podfile-validations : 0.2.0
cocoapods-generate                    : 2.2.5
cocoapods-imy-bin                     : 0.3.0.11
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.1
cocoapods-trunk                       : 1.6.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/cocoapods/specs.git'

#命令写在这里也是等效， 已移动到Podfile_local中，避免git提交冲突等场景
#plugin 'cocoapods-imy-bin'
#use_binaries!

target 'Demo' do
  pod 'FMDB'
  pod 'LKDBHelper'

  pod 'YYModel',:podspec => 'https://github.com/ibireme/YYModel/raw/master/YYModel.podspec'

  pod 'YYCache',:podspec => 'https://github.com/ibireme/YYCache/raw/master/YYCache.podspec'

  end
```

### Error

```
RuntimeError - Unable to find the default subcommand `open` for command `Pod::Command::Bin`.
/Users/username/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:368:in `load_default_subcommand'
/Users/username/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:354:in `parse'
/Users/username/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:352:in `parse'
/Users/username/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:330:in `run'
/Users/username/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.14.2/lib/cocoapods/command.rb:52:in `run'
/Users/username/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.14.2/bin/pod:55:in `<top (required)>'
/Users/username/.rvm/gems/ruby-3.0.0/bin/pod:25:in `load'
/Users/username/.rvm/gems/ruby-3.0.0/bin/pod:25:in `<main>'
/Users/username/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/username/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by lirs72379** [comment]
请见谅，这是我的自动回复邮件，您的邮件已收到，谢谢！
