### ISSUE TITLE
pod bin auto -> TypeError - no implicit conversion of Array into String

### ISSUE THREAD

**Issue by hengyangKing** [MeetYouDevs/cocoapods-imy-bin#26]
CocoaPods : 1.7.5
Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
RubyGems : 3.0.3

### Podfile

```ruby
plugin 'cocoapods-imy-bin'
use_binaries!
#set_use_source_pods ['Moya','SnapKit']

source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

use_frameworks!

target 'Swift-OC' do

#Swift库

#    pod 'Alamofire'
    pod 'Moya'
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'HandyJSON'
    pod 'lottie-ios'
    pod 'Toast'

#OC库

    pod 'MYLCommonUI', '~> 0.0.11'
    pod 'Masonry'

end
```

### Error

```
TypeError - no implicit conversion of Array into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

请问一下 是我的pod版本有问题么？执行pod bin auto 报错

**Comment by su350380433** [comment]
这个版本不支持这swift混编

**Comment by hengyangKing** [comment]
是只支持oc二进制么？还是项目中无法兼容swift存在的情况呢？

**Comment by su350380433** [comment]
> 是只支持oc二进制么？还是项目中无法兼容swift存在的情况呢？

1、目前版本 只支持OC二进制，
2、对于混编项目也是支持的，可以通过配置项开关过滤swift  相关Pods库，ArchiveBin.json

**Comment by hengyangKing** [comment]
### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.0
cocoapods-imy-bin                     : 0.2.9.1
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
platform :ios, '9.0'
plugin 'cocoapods-imy-bin'
use_binaries!

target 'BuildDemo' do
  use_frameworks!
  pod 'AFNetworking'
end
```

### Error

```
TypeError - no implicit conversion of Array into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by hengyangKing** [comment]
我这边在Podfile 内只引用一个oc库，并执行 pod bin auto 仍然报上述错误

**Comment by su350380433** [comment]
> 我这边在Podfile 内只引用一个oc库，并执行 pod bin auto 仍然报上述错误

目前版本不支持  use_frameworks!

**Comment by hengyangKing** [comment]
### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
```
### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.0
cocoapods-imy-bin                     : 0.2.9.1
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile
```ruby
plugin 'cocoapods-imy-bin'
use_binaries!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'BuildDemo' do

end
```
### Error

```
TypeError - no implicit conversion of Array into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
我这边使用一个空的Podfile，依然无法正常编译，不知是否是pod 或 pod 插件版本有问题呢？

**Comment by hengyangKing** [comment]
> 检查一下您的环境，或者升级到1.8.4的pod

我这边升级到高版本的pod确实是可以完成编译，

**Comment by hengyangKing** [comment]
> 检查一下您的环境，或者升级到1.8.4的pod

我这边升级到高版本的pod确实是可以完成编译，谢谢
