### ISSUE TITLE
项目集成RN后，制作二进制失败

### ISSUE THREAD

**Issue by boduoduo** [MeetYouDevs/cocoapods-imy-bin#47]
我们项目集成了RN，是制作二进制组件的时候报了一个错

### Error
```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/xxx/Documents/xxx-build-temp/bin-archive/xxx/RN/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `open'

podfile里面这么写的:
pod 'BVLinearGradient', :podspec => 'RN/node_modules/react-native-linear-gradient/BVLinearGradient.podspec'
这个要怎么处理，大佬？
在Podfile_local,里面 set_use_source_pods ['BVLinearGradient'],貌似也不行

**Comment by su350380433** [comment]
找不到库？

**Comment by boduoduo** [comment]
项目引入的DoubleConversion，他的podspec文件是在RN文件中node_modules里面的，我看报错的意思是，在bin-archive里面没找到DoubleConversion的podspec文件

**Comment by su350380433** [comment]
把这个库配置在白名单里面

**Comment by boduoduo** [comment]
我在BinArchive.json文件里面加了
```
{
  "//": "archive-white-pod-list 不制作二进制白名单，",
  "archive-white-pod-list" : [
      "BVLinearGradient",
      "DoubleConversion"
  ],
  "//": "ignore-git-list 不制作二进制 所属git白名单，",
  "ignore-git-list": [

  ],
   "//": "ignore-http-list 不制作二进制 所属https白名单，",
  "ignore-http-list": [

  ],
  "//": "xcode_build_path 设置编译缓存完整路径, 默认地址如下"
}
```
但是执行完pod bin auto --all-make 还是会报这个错
### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/xxx/Documents/Git:xxx-build-temp/bin-archive/xxxx/RN/node_modules/react-native-linear-gradient/BVLinearGradient.podspec
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/installer.rb:62:in `block (3 levels) in install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:41:in `with_changes'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/installer.rb:54:in `block (2 levels) in install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/installer.rb:53:in `block in install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/installer.rb:40:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/command/gen.rb:68:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/command/gen.rb:67:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/command/gen.rb:67:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:166:in `block (2 levels) in generate_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:153:in `block in generate_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:152:in `generate_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:124:in `run_archive'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:53:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by su350380433** [comment]
在主工程下podspec文件是否有加入 对这个RN库的依赖，s.dependency

**Comment by boduoduo** [comment]
没有加
