### ISSUE TITLE
三方SDK通过pod导入怎么能忽略这些库？

### ISSUE THREAD

**Issue by Hajarwith** [MeetYouDevs/cocoapods-imy-bin#66]
例如友盟的，我加如忽略文件中，在执行pod bin install 的时候一直提示错误。。。

**Comment by su350380433** [comment]
配置白名单

**Comment by Hajarwith** [comment]
配置完白名单  我早pod bin install  的时候一直报错找不着,想问问这我是错哪儿了  


Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only
  perfomed in repo update
[!] Unable to find a specification for `UMCCommon`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Hajarwith** [comment]
大佬儿   那个忽略有没有需要注意的呢  因为我这边把那些三方SDK 移除以后  就可以执行了

**Comment by dabing1022** [comment]
方便的话可以提供下podspec 以及 Podfile 、Podfile_local文件
从现状上看 `UMCCommon` 库在索引库中找不到。具体排查方式你可以通过`pod env`或者`pod repo list`查看你的索引库，看看这几个索引库中是否有`UMCCommon`。

**Comment by Hajarwith** [comment]
pod 'SDWebImageFLPlugin'
 pod 'SDWebImageWebPCoder' 
 
您好 我现在项目中用到了这两个库  在pod bin install  的时候一直报错   只要把这两个库注释掉其他的 都可以自由转换    
 
我它两单独拿出进行操作不能成功  您能帮忙看看吗？

**Comment by Hajarwith** [comment]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin update --all-make
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.2.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.29.2
Ruby lib dir : /usr/local/Cellar/ruby/2.7.2/lib
Repositories : hajarwith - git - https://github.com/Hajarwith/devSouce.git @ 69a527cf5c3f155942269f8d8c7419d6feaa0a98

               hajarwith-1 - git - https://github.com/Hajarwith/masterDev.git @ 82d5952a051cbd21072fecd5a597ade0b1b39d5b

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.1.3
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
target 'Demo' do


  pod 'SDWebImageFLPlugin', :git => 'https://github.com/SDWebImage/SDWebImageFLPlugin.git'
  pod 'SDWebImageWebPCoder', :git => 'https://github.com/SDWebImage/SDWebImageWebPCoder.git'

end
```

### Error

```
NoMethodError - undefined method `each' for nil:NilClass
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:749:in `block (2 levels) in dependencies_for_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:748:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:748:in `block in dependencies_for_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:747:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:747:in `dependencies_for_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:687:in `block in compute_pod_target_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:686:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:686:in `compute_pod_target_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:652:in `generate_pod_targets'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:431:in `generate_targets'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:127:in `analyze'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/installer.rb:62:in `block (3 levels) in install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/config.rb:41:in `with_changes'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/installer.rb:54:in `block (2 levels) in install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/installer.rb:53:in `block in install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:118:in `title'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/installer.rb:40:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/command/gen.rb:68:in `block in run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/command/gen.rb:67:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/command/gen.rb:67:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:176:in `block (2 levels) in generate_project'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:155:in `block in generate_project'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:154:in `generate_project'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:129:in `run_archive'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:57:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60each%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NoMethodError - undefined method `size' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/10273 [closed] [3 comments]
   a week ago

 - undefined method `map' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/10301 [closed] [1 comment]
   3 weeks ago

 - NoMethodError - undefined method `real_path`
   https://github.com/CocoaPods/CocoaPods/issues/8082 [open] [13 comments]
   25 Feb 2019

and 189 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60each%27%20for%20nil&type=Issues&utf8=✓

[!] ====== cocoapods-imy-bin 0.3.1.3 版本 ========


[!] ======  dev 环境 ========

**Comment by dabing1022** [comment]
> Command
> /usr/local/bin/pod bin update --all-make

`pod bin update --all-make` ? 命令打错了吧

**Comment by Hajarwith** [comment]
命令没问题的 
执行的是 pod bin install

**Comment by Hajarwith** [comment]
### Command

```
/usr/local/bin/pod bin update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

**Comment by robinchanme** [comment]
是因为 sdwebimage/core
