### ISSUE TITLE
NoMethodError - undefined method `sources_option' for #<Pod::Command::Bin::Auto:0x00007f807d0b2048> 

### ISSUE THREAD

**Issue by miroda** [MeetYouDevs/cocoapods-imy-bin#84]
```
NoMethodError - undefined method `sources_option' for #<Pod::Command::Bin::Auto:0x00007f807d0b2048>
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.2/lib/cocoapods-imy-bin/command/bin/auto.rb:97:in `run_archive'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.2/lib/cocoapods-imy-bin/command/bin/auto.rb:57:in `run'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users//.rvm/rubies/ruby-2.6.0/bin/pod:23:in `load'
/Users//.rvm/rubies/ruby-2.6.0/bin/pod:23:in `<main>'
/Users//.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
/Users//.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by miroda** [comment]
Error loading the plugin `cocoapods-imy-bin-0.3.1.2`.

LoadError - cannot load such file -- cocoapods-imy-bin/command/bin/local

**Comment by su350380433** [comment]
更新0.3.1.3

**Comment by miroda** [comment]
done
