### ISSUE TITLE
TypeError - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by RichardClay** [MeetYouDevs/cocoapods-imy-bin#90]
能说一下项目基本配置的RVM 和Ruby的版本吗？ 会出现不兼容的情况。
TypeError - no implicit conversion of nil into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by y2kbug** [comment]
CocoaPods 看到类似issue说是iterm2 bug，重启下iterm2,试试

**Comment by RichardClay** [comment]
> CocoaPods 看到类似issue说是iterm2 bug，重启下iterm2,试试

重启过了，还是不行，我感觉是ruby环境和rvm的问题，你看一下你们环境的ruby、rvm版本，我这边ruby是2.7的版本  不是3 ，是不是太低了导致的

**Comment by y2kbug** [comment]
> > CocoaPods 看到类似issue说是iterm2 bug，重启下iterm2,试试
> 
> 重启过了，还是不行，我感觉是ruby环境和rvm的问题，你看一下你们环境的ruby、rvm版本，我这边ruby是2.7的版本 不是3 ，是不是太低了导致的

![image](https://user-images.githubusercontent.com/1960051/104531223-a58c4700-5648-11eb-8db5-1fe37b37cec8.png)

**Comment by RichardClay** [comment]
> > > CocoaPods 看到类似issue说是iterm2 bug，重启下iterm2,试试
> > 
> > 
> > 重启过了，还是不行，我感觉是ruby环境和rvm的问题，你看一下你们环境的ruby、rvm版本，我这边ruby是2.7的版本 不是3 ，是不是太低了导致的
> 
> ![image](https://user-images.githubusercontent.com/1960051/104531223-a58c4700-5648-11eb-8db5-1fe37b37cec8.png)

一样的...

**Comment by dabing1022** [comment]
发下你的`pod bin auto`执行的文件目录截图。提问问题注意提供下相关日志、相关截图，帮助他人更好的理解问题。

**Comment by RichardClay** [comment]
> 发下你的`pod bin auto`执行的文件目录截图。提问问题注意提供下相关日志、相关截图，帮助他人更好的理解问题。

![image](https://user-images.githubusercontent.com/16526912/104537977-f8b8c680-5655-11eb-9600-0be44030a076.png)

**Comment by dabing1022** [comment]
看了下 没有按照imy-bin目前的打包思路来。建议先看下作者提供的demo项目。Podfile、podspec在一个文件夹中。

**Comment by dabing1022** [comment]
![image](https://user-images.githubusercontent.com/1892303/104567293-98437c80-5689-11eb-91f3-ab588aebcdfc.png)

已经成功了 我这边没问题 有个代码问题 我这边还需要和 @su350380433 核对下

**Comment by RichardClay** [comment]
![image](https://user-images.githubusercontent.com/16526912/104572777-122a3480-568f-11eb-8843-9cd29026acad.png)
现在push失败了

**Comment by dabing1022** [comment]
可以发下podfile、podspec的内容，方便帮你分析问题。目前看libapp.a没有生成。

**Comment by RichardClay** [comment]
> 可以发下podfile、podspec的内容，方便帮你分析问题。目前看libapp.a没有生成。

我用的是demo里面的

**Comment by bolee** [comment]
我的出现了，是pod安装问题，重新用gem都装一遍

**Comment by looha518** [comment]
求教 最后怎么解决的
