### ISSUE TITLE
开启use_modular_headers! 出现如下错误

### ISSUE THREAD

**Issue by Serlight** [MeetYouDevs/cocoapods-imy-bin#91]
````
NoMethodError - undefined method `each' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:134:in `block (3 levels) in podfile_for_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:133:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:133:in `block (2 levels) in podfile_for_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:123:in `instance_exec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:123:in `block in podfile_for_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:50:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `podfile_for_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/podfile_generator.rb:22:in `block in podfiles_by_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/podfile_generator.rb:21:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/podfile_generator.rb:21:in `podfiles_by_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/command/gen.rb:67:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/archive.rb:172:in `block (2 levels) in generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/archive.rb:155:in `block in generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/archive.rb:154:in `generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/auto.rb:129:in `run_archive'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/auto.rb:57:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'`

当我在混编的demo里面, 开启了**use_modular_headers!**, 在执行 **pod bin auto** 的时候会有上面的错误
`use_modular_headers!`

**Comment by dabing1022** [comment]
版本cocoapods-imy-bin-0.3.1.4 ?

**Comment by Serlight** [comment]
我本地拉了最新代码打的

**Comment by su350380433** [comment]
欢迎PR

**Comment by BlueSkyInwind** [comment]
> ```
> NoMethodError - undefined method `each' for nil:NilClass
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:134:in `block (3 levels) in podfile_for_spec'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:133:in `each'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:133:in `block (2 levels) in podfile_for_spec'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:123:in `instance_exec'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:123:in `block in podfile_for_spec'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:50:in `initialize'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `new'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `podfile_for_spec'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/podfile_generator.rb:22:in `block in podfiles_by_spec'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/podfile_generator.rb:21:in `map'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/generate/podfile_generator.rb:21:in `podfiles_by_spec'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.1/lib/cocoapods/command/gen.rb:67:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/archive.rb:172:in `block (2 levels) in generate_project'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/archive.rb:155:in `block in generate_project'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/archive.rb:154:in `generate_project'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/auto.rb:129:in `run_archive'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.1.4/lib/cocoapods-imy-bin/command/bin/auto.rb:57:in `run'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'
> ```
> 
> 
> 当我在混编的demo里面开启了 **use_modular_headers!** , 在执行 **pod bin auto** 的时候会有上面的错误
> 
> 
> `use_modular_headers!`

我也遇到同样的问题，请问下，你这边解决了吗？
