### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Hajarwith** [MeetYouDevs/cocoapods-imy-bin#93]
pod 'SDWebImageFLPlugin'
 pod 'SDWebImageWebPCoder'
引入这两个库的时候一直报错  无法进行下去  

pod bin install 

 Demo pod bin install
Analyzing dependencies
====== cocoapods-imy-bin 0.3.1.3 版本 ========

======  dev 环境 ========

======  dev 环境 ========

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.2.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.29.2
Ruby lib dir : /usr/local/Cellar/ruby/2.7.2/lib
Repositories : hajarwith - git - https://github.com/Hajarwith/devSouce.git @ 69a527cf5c3f155942269f8d8c7419d6feaa0a98

               hajarwith-1 - git - https://github.com/Hajarwith/masterDev.git @ 82d5952a051cbd21072fecd5a597ade0b1b39d5b

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.1.3
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

**Comment by y2kbug** [comment]
贴日志不完整，完全没看到什么错误

**Comment by Hajarwith** [comment]
Analyzing dependencies
====== cocoapods-imy-bin 0.3.1.3 版本 ========

======  dev 环境 ========

======  dev 环境 ========

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.2.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.29.2
Ruby lib dir : /usr/local/Cellar/ruby/2.7.2/lib
Repositories : hajarwith - git - https://github.com/Hajarwith/devSouce.git @ 69a527cf5c3f155942269f8d8c7419d6feaa0a98

               hajarwith-1 - git - https://github.com/Hajarwith/masterDev.git @ 82d5952a051cbd21072fecd5a597ade0b1b39d5b

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.1.3
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
target 'Demo' do


  pod 'SDWebImage'
  pod 'libwebp'
  pod 'FLAnimatedImage'
  pod 'SDWebImageFLPlugin'
  pod 'SDWebImageWebPCoder'

end
```

### Error

```
NoMethodError - undefined method `each' for nil:NilClass
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:749:in `block (2 levels) in dependencies_for_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:748:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:748:in `block in dependencies_for_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:747:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:747:in `dependencies_for_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:687:in `block in compute_pod_target_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:686:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:686:in `compute_pod_target_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:652:in `generate_pod_targets'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:431:in `generate_targets'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:127:in `analyze'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/install.rb:39:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60each%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NoMethodError - undefined method `size' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/10273 [closed] [3 comments]
   a week ago

 - undefined method `map' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/10301 [closed] [1 comment]
   3 weeks ago

 - NoMethodError - undefined method `real_path`
   https://github.com/CocoaPods/CocoaPods/issues/8082 [open] [13 comments]
   25 Feb 2019

and 190 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60each%27%20for%20nil&type=Issues&utf8=✓

**Comment by Hajarwith** [comment]
你那边能用这两个库吗？   我这边其他的都好使  就是它两了

**Comment by dabing1022** [comment]
![image](https://user-images.githubusercontent.com/1892303/104554366-0e8ab380-5677-11eb-9e7b-ef9276f9ce5b.png)
我还在研究 这边测试build-arch目录中都是framework，导致lipo静态库的时候会出问题。

**Comment by Hajarwith** [comment]
大佬儿  辛苦~

**Comment by dabing1022** [comment]
![image](https://user-images.githubusercontent.com/1892303/104567293-98437c80-5689-11eb-91f3-ab588aebcdfc.png)

![image](https://user-images.githubusercontent.com/1892303/104567449-c1640d00-5689-11eb-84ce-ea154e162738.png)

已经成功了 我这边没问题 有个代码问题 我这边还需要和 @su350380433 核对下

**Comment by Hajarwith** [comment]
我这边是需要更新下cocoapods-imy-bin吗？

**Comment by dabing1022** [comment]
> 我这边是需要更新下cocoapods-imy-bin吗？

代码还没修复合并。稍微再等等

**Comment by Hajarwith** [comment]
大佬儿  现在更新好使吗？   我重新安装了下   貌似还是不行

**Comment by dabing1022** [comment]
作者还没发版。我这边用的master安装的

**Comment by Hajarwith** [comment]
好的   哈哈哈  有些迫不及待的想试试

**Comment by miroda** [comment]
> 好的 哈哈哈 有些迫不及待的想试试

可以直接用master安装

**Comment by Hajarwith** [comment]
嗯的 嗯的  感谢感谢  哈哈哈哈
